### PR TITLE
Use the icon size that matches the interface size

### PR DESCRIPTION
**Pull request by es20490446e**
Before and after:

Screenshot_20210227_171335

### CODE REVIEW

**Comment by AXeL-dev** [comment]
LGTM! Thanks @es20490446e !

**Comment by es20490446e** [comment]
You are welcome 👌😉

**Comment by es20490446e** [comment]
@AXeL-dev Remember to update at addons.mozilla.org.

**Comment by AXeL-dev** [comment]
@es20490446e sure! i'll do it this weekend.

**Comment by es20490446e** [comment]
Thanks 👍👍

**Comment by AXeL-dev** [comment]
@es20490446e Done! thanks again for your help :wink:

**Comment by es20490446e** [comment]
Yeah, now it looks great! 👍

**Pull request merged**
